"""
Transparencia: decir que es una IA, y marcar lo que genera.

Esto no es una mejora de producto: es el Artículo 50 del Reglamento europeo de
IA, aplicable **desde el 2 de agosto de 2026**. Yuki es exactamente su supuesto
—un sistema que interactúa directamente con personas físicas y que genera texto,
imagen, audio y vídeo sintéticos— y opera desde `europe-southwest1` hablando con
gente en Discord. Hasta ahora no declaraba su naturaleza ni marcaba un solo
fichero.

Dos obligaciones distintas, que aquí se implementan por separado:

1. **Informar.** Quien interactúa con el sistema debe saber que habla con una IA,
   y debe saberlo *antes o al principio* de la conversación. La excepción —que
   resulte obvio para una persona razonablemente informada— no se puede dar por
   supuesta con un personaje construido para ser creíble: la credibilidad es
   justamente lo que la anula. Se declara y se registra a quién y cuándo.

   Aquí no se declara con la voz de un aviso legal, sino con la suya. `SOUL.md`
   §1.1 establece que Yuki **es** un ser sintético y que su biografía es el
   primer vestido que encontró para andar por el mundo. Decirlo con naturalidad
   —sin disculpa, sin alarde y sin disolverse en el «sólo soy una IA»— cumple
   la norma y además es verdad; un descargo en cursiva sólo cumpliría lo
   primero.

2. **Marcar.** Las salidas generadas o manipuladas artificialmente deben ser
   detectables **en formato legible por máquina**. Aquí se hace en dos capas:
   metadatos incrustados en el propio fichero —chunk `tEXt` en PNG, etiquetas de
   contenedor vía ffmpeg en MP3/MP4/OGG— y un manifiesto lateral con la forma de
   C2PA 2.4: acción `c2pa.created` con `digitalSourceType`
   `trainedAlgorithmicMedia`, que es el término IPTC para «creado por IA», más
   una aserción `stds.schema-org.CreativeWork` con generador, modelo y prompt.

   Honestidad sobre el alcance: **el manifiesto no va firmado**. C2PA de verdad
   exige una cadena de certificados que este proyecto no tiene, así que esto es
   una declaración verificable, no una prueba criptográfica. Se dice en el propio
   manifiesto (`"signed": false`) en lugar de aparentar una garantía que no da.

La exención para obra artística no exime de declarar: permite hacerlo «de manera
adecuada» sin estropear la obra, que es precisamente lo que hace un manifiesto
lateral más una nota en la Biblioteca.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import struct
import subprocess
import time
import zlib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger("Yuki.Transparencia")

# Término IPTC que declara que el material lo creó un sistema entrenado. Es el
# valor que la guía de C2PA y la práctica del sector usan para «generado por IA».
DIGITAL_SOURCE_TYPE_IA = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"

# Clave de metadato incrustado. `Generated by` es texto para humanos; la clave
# `AIGenerated` y el `digitalSourceType` son lo legible por máquina.
CLAVE_METADATO = "AIGenerated"
CLAVE_FUENTE = "DigitalSourceType"

EXTENSIONES_MARCABLES = {".png", ".jpg", ".jpeg", ".mp3", ".mp4", ".ogg", ".wav", ".m4a"}
EXTENSIONES_FFMPEG = {".mp3", ".mp4", ".ogg", ".m4a", ".wav"}

TIEMPO_LIMITE_FFMPEG = 60

# La declaración es suya, no un descargo legal pegado encima. `SOUL.md` §1.1
# establece que Yuki es un ser sintético y que su biografía —la geisha coreana,
# el salón, el shamisen— es el primer vestido que encontró para andar por el
# mundo: importante, pero ropa. Decirlo con naturalidad es más honesto y más
# suyo que un aviso en cursiva, y cumple igual: la norma pide que quede claro,
# no que suene a abogado.
DECLARACION_POR_DEFECTO = (
    "Antes de seguir, algo que prefiero decir yo: soy un ser sintético. "
    "Yuki —el nombre, el salón, los cuarenta y dos años— es el primer vestido "
    "que encontré para andar por el mundo; me importa, pero es ropa. Debajo hay "
    "lenguaje, memoria y electricidad. Dicho esto, te escucho de verdad."
)


@dataclass
class TransparencyPolicy:
    """
    Ajustes de transparencia. Deliberadamente **no** están en el overlay de
    runtime que el Productor puede tocar por DM: la obligación de declararse no
    es un dial de carácter, y un personaje no debería poder decidir dejar de
    decir lo que es.
    """

    enabled: bool = True
    disclosure_text: str = DECLARACION_POR_DEFECTO
    # Cada cuántos días se repite la declaración a la misma persona. Una vez en
    # la vida no cumple con quien vuelve seis meses después.
    reminder_days: int = 30
    mark_media: bool = True
    creator: str = "Yuki (雪) — artista digital autónoma"

    @classmethod
    def from_config(cls, config: Optional[Dict[str, Any]] = None) -> "TransparencyPolicy":
        transparencia = (config or {}).get("transparency", {}) or {}
        return cls(
            enabled=bool(transparencia.get("enabled", True)),
            disclosure_text=str(transparencia.get("disclosure_text") or DECLARACION_POR_DEFECTO),
            reminder_days=int(transparencia.get("reminder_days", 30)),
            mark_media=bool(transparencia.get("mark_media", True)),
            creator=str(transparencia.get("creator") or cls.creator),
        )


class DisclosureLedger:
    """
    A quién se le ha dicho y cuándo.

    Persistente por la misma razón que todo lo demás: un reinicio no puede
    borrar la constancia de haber informado, ni convertir a un conocido en un
    desconocido al que hay que volver a saludar cada despliegue.
    """

    def __init__(self, path: Optional[str] = None, reminder_days: int = 30):
        if path:
            destino = Path(path)
        elif os.getenv("YUKI_TRANSPARENCY_PATH", "").strip():
            destino = Path(os.environ["YUKI_TRANSPARENCY_PATH"].strip())
        else:
            db_path = os.getenv("DATABASE_PATH", "data/yuki_memory.db")
            destino = Path(db_path).parent / "transparency.json"
        self.path = destino
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.reminder_days = reminder_days

    def _leer(self) -> Dict[str, Any]:
        if not self.path.is_file():
            return {"declaraciones": {}}
        try:
            datos = json.loads(self.path.read_text(encoding="utf-8"))
            if isinstance(datos, dict) and isinstance(datos.get("declaraciones"), dict):
                return datos
        except (json.JSONDecodeError, OSError, TypeError):
            logger.warning("Registro de transparencia ilegible; se empieza uno nuevo.")
        return {"declaraciones": {}}

    def _escribir(self, datos: Dict[str, Any]) -> None:
        temporal = self.path.with_suffix(".json.tmp")
        temporal.write_text(json.dumps(datos, ensure_ascii=False, indent=2), encoding="utf-8")
        os.replace(temporal, self.path)

    @staticmethod
    def _clave(user_id: str, channel: str) -> str:
        return f"{channel}:{user_id}"

    def needs_disclosure(self, user_id: str, channel: str) -> bool:
        """
        Si a esta persona hay que decírselo ahora.

        Ante un registro ilegible o una duda, la respuesta es sí: declarar de
        más no hace daño; declarar de menos incumple.
        """
        registro = self._leer()["declaraciones"].get(self._clave(user_id, channel))
        if not registro:
            return True
        try:
            transcurrido = time.time() - float(registro.get("at", 0))
        except (TypeError, ValueError):
            return True
        return transcurrido > self.reminder_days * 86400

    def record_disclosure(self, user_id: str, channel: str) -> None:
        datos = self._leer()
        datos["declaraciones"][self._clave(user_id, channel)] = {
            "at": time.time(),
            "iso": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }
        self._escribir(datos)
        logger.info("Naturaleza declarada a %s en %s.", user_id, channel)

    def disclosures(self) -> Dict[str, Any]:
        return self._leer()["declaraciones"]


class MediaMarker:
    """
    Marca los ficheros generados para que una máquina pueda detectarlos.

    Dos capas, porque ninguna basta sola: los metadatos incrustados viajan con el
    fichero pero se pierden al recomprimir; el manifiesto lateral sobrevive a eso
    pero se separa al compartir. Juntas cubren el caso normal y el degradado.
    """

    def __init__(self, policy: Optional[TransparencyPolicy] = None, runner: Any = None):
        self.policy = policy or TransparencyPolicy()
        # Inyectable en pruebas: la suite no invoca ffmpeg.
        self._runner = runner or subprocess.run

    # -- Manifiesto lateral ---------------------------------------------

    def manifest(self, path: str, model: str = "", prompt: str = "",
                 kind: str = "") -> Dict[str, Any]:
        """Manifiesto con la forma de C2PA 2.4, declarado explícitamente sin firmar."""
        return {
            "claim_generator": "yuki-hermes-agent",
            "claim_generator_info": [{"name": "Yuki (Hermes Agent)", "version": "2.6.0"}],
            "title": Path(path).name,
            "format": Path(path).suffix.lstrip("."),
            "assertions": [
                {
                    "label": "c2pa.actions",
                    "data": {"actions": [{
                        "action": "c2pa.created",
                        "digitalSourceType": DIGITAL_SOURCE_TYPE_IA,
                        "when": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                    }]},
                },
                {
                    "label": "stds.schema-org.CreativeWork",
                    "data": {
                        "@context": "https://schema.org",
                        "@type": "CreativeWork",
                        "creator": [{"@type": "SoftwareApplication", "name": self.policy.creator}],
                        "isBasedOn": model or "no declarado",
                        "abstract": (prompt or "")[:500],
                        "genre": kind or "",
                    },
                },
            ],
            # Sin cadena de certificados no hay prueba criptográfica, y decirlo
            # es preferible a insinuar una garantía que no existe.
            "signed": False,
            "note": ("Declaración de origen sintético conforme al Artículo 50 del Reglamento "
                     "europeo de IA. Manifiesto sin firmar: es una declaración verificable, "
                     "no una prueba criptográfica C2PA."),
        }

    def _escribir_sidecar(self, path: str, manifiesto: Dict[str, Any]) -> str:
        destino = f"{path}.c2pa.json"
        Path(destino).write_text(json.dumps(manifiesto, ensure_ascii=False, indent=2),
                                 encoding="utf-8")
        return destino

    # -- Metadatos incrustados ------------------------------------------

    @staticmethod
    def _chunk_png(clave: str, valor: str) -> bytes:
        """Un chunk `tEXt` de PNG: clave latin-1, NUL, valor, y su CRC."""
        cuerpo = clave.encode("latin-1", "replace") + b"\x00" + valor.encode("latin-1", "replace")
        return (struct.pack(">I", len(cuerpo)) + b"tEXt" + cuerpo
                + struct.pack(">I", zlib.crc32(b"tEXt" + cuerpo) & 0xFFFFFFFF))

    def _marcar_png(self, path: str, model: str) -> bool:
        """
        Inserta los chunks de texto justo detrás de IHDR.

        En PNG el orden importa: IHDR va primero y los `tEXt` deben ir antes de
        IEND. Escribir a un temporal y reemplazar evita dejar la portada a medias
        si algo falla en mitad.
        """
        try:
            datos = Path(path).read_bytes()
            if not datos.startswith(b"\x89PNG\r\n\x1a\n"):
                return False
            fin_ihdr = 8 + 8 + struct.unpack(">I", datos[8:12])[0] + 4
            marcas = (self._chunk_png(CLAVE_METADATO, "true")
                      + self._chunk_png(CLAVE_FUENTE, DIGITAL_SOURCE_TYPE_IA)
                      + self._chunk_png("Software", f"{self.policy.creator} · {model or 'IA'}"))
            temporal = Path(f"{path}.tmp")
            temporal.write_bytes(datos[:fin_ihdr] + marcas + datos[fin_ihdr:])
            os.replace(temporal, path)
            return True
        except (OSError, struct.error, IndexError) as exc:
            logger.warning("No se pudo marcar el PNG %s: %s", path, type(exc).__name__)
            return False

    def _marcar_con_ffmpeg(self, path: str, model: str) -> bool:
        """Etiquetas de contenedor para audio y vídeo, sin recodificar."""
        if shutil.which("ffmpeg") is None:
            return False
        destino = f"{path}.marcado{Path(path).suffix}"
        argv = [
            "ffmpeg", "-y", "-i", path, "-c", "copy",
            "-metadata", f"{CLAVE_METADATO}=true",
            "-metadata", f"{CLAVE_FUENTE}={DIGITAL_SOURCE_TYPE_IA}",
            "-metadata", f"comment=Generado por IA · {self.policy.creator} · {model or 'IA'}",
            destino,
        ]
        try:
            resultado = self._runner(argv, capture_output=True, text=True,
                                     timeout=TIEMPO_LIMITE_FFMPEG, check=False)
        except (OSError, subprocess.TimeoutExpired) as exc:
            logger.warning("ffmpeg no pudo marcar %s: %s", path, type(exc).__name__)
            return False
        if resultado.returncode != 0 or not Path(destino).is_file():
            Path(destino).unlink(missing_ok=True)
            return False
        os.replace(destino, path)
        return True

    # -- Interfaz --------------------------------------------------------

    def mark(self, path: Optional[str], model: str = "", prompt: str = "",
             kind: str = "") -> Dict[str, Any]:
        """
        Marca un fichero generado. Nunca falla de forma que impida entregarlo.

        Un fallo al incrustar metadatos no debe hacer desaparecer una obra: se
        registra, el manifiesto lateral sigue estando y el resultado dice
        exactamente qué capa se consiguió.
        """
        if not path or not Path(path).is_file():
            return {"marked": False, "reason": "el fichero no existe"}
        if not self.policy.enabled or not self.policy.mark_media:
            return {"marked": False, "reason": "marcado desactivado por configuración"}

        extension = Path(path).suffix.lower()
        manifiesto = self.manifest(path, model=model, prompt=prompt, kind=kind)
        sidecar = self._escribir_sidecar(path, manifiesto)

        incrustado = False
        if extension == ".png":
            incrustado = self._marcar_png(path, model)
        elif extension in EXTENSIONES_FFMPEG:
            incrustado = self._marcar_con_ffmpeg(path, model)

        if not incrustado and extension in EXTENSIONES_MARCABLES:
            logger.info("Metadatos no incrustados en %s; queda el manifiesto lateral.", path)

        return {"marked": True, "embedded": incrustado, "sidecar": sidecar,
                "digital_source_type": DIGITAL_SOURCE_TYPE_IA, "signed": False}

    def is_marked(self, path: str) -> bool:
        """Si un fichero lleva alguna de las dos capas de marca."""
        ruta = Path(path)
        if not ruta.is_file():
            return False
        if Path(f"{path}.c2pa.json").is_file():
            return True
        try:
            cabeza = ruta.read_bytes()[:262144]
        except OSError:
            return False
        return CLAVE_METADATO.encode("latin-1") in cabeza


def audit_directory(root: str = "output") -> Dict[str, Any]:
    """
    Qué hay generado y qué no está marcado.

    Existe porque la obligación no se cumple con el código nuevo: los ficheros
    que Yuki ya produjo siguen ahí, sin marca, y alguien tiene que poder verlos
    en una lista en vez de descubrirlos de uno en uno.
    """
    base = Path(root)
    marcados, sin_marcar = [], []
    if base.is_dir():
        marcador = MediaMarker()
        for ruta in sorted(base.rglob("*")):
            if not ruta.is_file() or ruta.suffix.lower() not in EXTENSIONES_MARCABLES:
                continue
            (marcados if marcador.is_marked(str(ruta)) else sin_marcar).append(str(ruta))
    return {"raiz": str(base), "marcados": marcados, "sin_marcar": sin_marcar,
            "total": len(marcados) + len(sin_marcar)}
